---
module_1:
  container:
    simg_name: dgcnn_single_plant_soil_segmentation.simg
    dockerhub_path: docker://phytooracle/dgcnn_single_plant_soil_segmentation:latest
  command: singularity run -B $(pwd):/mnt --pwd /mnt dgcnn_single_plant_soil_segmentation.simg -i ${PLANT_NAME} --model_path ${MODEL_PATH}
  output_dir: individual_plants_out/combined_pointclouds

module_2:
  container: 
    simg_name: 3d_neighbor_removal.simg
    dockerhub_path: docker://phytooracle/3d_neighbor_removal:latest
  command: singularity run -B $(pwd):/mnt --pwd /mnt 3d_neighbor_removal.simg -i ${PLANT_NAME} -e 0.03
  output_dir: individual_plants_out/combined_pointclouds