---
tags:
  pipeline: kmeans_cropping
  description: dev
  notes: Initial development of K-means cropping approach.

modules:
  1:
    container:
      simg_name: dgcnn_single_plant_soil_segmentation.simg
      dockerhub_path: docker://phytooracle/dgcnn_single_plant_soil_segmentation:latest
    command: singularity run -B $(pwd):/mnt --pwd /mnt dgcnn_single_plant_soil_segmentation.simg -i ${PLANT_NAME} --model_path ${MODEL_PATH}
    output_dir: individual_plants_out #/segmentation_pointclouds

  2:
    container: 
      simg_name: 3d_neighbor_removal.simg
      dockerhub_path: docker://phytooracle/3d_neighbor_removal:latest
    command: singularity run -B $(pwd):/mnt --pwd /mnt 3d_neighbor_removal.simg -i ${PLANT_NAME} -e 0.03
    output_dir: individual_plants_out #/segmentation_pointclouds
  
  3:
    container: 
      simg_name: 3d_entropy_features.simg
      dockerhub_path: docker://phytooracle/3d_entropy_features:latest
    command: singularity run -B $(pwd):/mnt --pwd /mnt 3d_entropy_features.simg -o combined_pointclouds/${PLANT_NAME} -f ${PLANT_NAME}_hull_volumes -p individual_plants_out/combined_pointclouds/${PLANT_NAME}/*_plant_clustered.ply
    output_dir: individual_plants_out #/segmentation_pointclouds

paths:
  pipeline_outpath:
    pointclouds: segmentation_pointclouds #../{date}/{concatenated_tag}/
    dashboard: plant_reports #../{date}/{concatendated_tag}/

  cyverse: 
    input: 
      basename: /iplant/home/shared/phytooracle/season_10_lettuce_yr_2020/level_1/scanner3DTop/
      subdir: test_set/
      suffix: _test_set.tar.gz
    output: 
      base: /iplant/home/shared/phytooracle/season_10_lettuce_yr_2020/level_2/scanner3DTop/
      subdir: segmentation_pointclouds



